redirect:
  enabled: true
  to: pangeo.informaticslab.co.uk
  from:
  - 'jupyterhub.informaticslab.co.uk'
  - 'jupyter.informaticslab.co.uk'

pangeo:
  jupyterhub:    
    ingress:
      hosts:
      - pangeo.informaticslab.co.uk
      tls:
        - hosts:
          - pangeo.informaticslab.co.uk
          secretName: kubelego-tls-proxy-pangeo.informaticslab.co.uk

    auth:
      github:
        callbackUrl: "https://pangeo.informaticslab.co.uk/hub/oauth_callback"
