
redirect:
  enabled: false

voila:
  enabled: false

pangeo:
  jupyterhub:
    ingress:
      hosts:
      - pangeo-hackathon.informaticslab.co.uk
      tls:
        - hosts:
          - pangeo-hackathon.informaticslab.co.uk
          secretName: tls-pangeo-hackathon.informaticslab.co.uk

    auth:
      github:
        callbackUrl: "https://pangeo-hackathon.informaticslab.co.uk/hub/oauth_callback"
        org_whitelist: null  # Disable the default org whitelist

  singleuser:
    extraEnv:
      INTAKE_PATH: "/s3/informatics-pangeo-data/catalogs/weather:/s3/informatics-pangeo-data/catalogs/climate:/s3/informatics-pangeo-data/catalogs/hackathon"
