
redirect:
  enabled: false

voila:
  enabled: false

pangeo:
  jupyterhub:
    ingress:
      hosts:
      - hackathon.informaticslab.co.uk
      tls:
        - hosts:
          - hackathon.informaticslab.co.uk
          secretName: cermanager-tls-pangeo-hackathon

    auth:
      github:
        callbackUrl: "https://hackathon.informaticslab.co.uk/hub/oauth_callback"
        org_whitelist: null  # Disable the default org whitelist

    hub:
      extraVolumes:
        - name: custom-templates
          gitRepo:
            repository: "https://github.com/met-office-lab/jade-custom-jupyterhub-templates.git"
            revision: "540f8be9e25e810d85269395409b3b22f1fd8ddc"

    singleuser:
      extraEnv:
        INTAKE_PATH: "/s3/informatics-pangeo-data/catalogs/weather:/s3/informatics-pangeo-data/catalogs/climate:/s3/informatics-pangeo-data/catalogs/hackathon"
