{{- if .Values.voila.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: voila
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: voila
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    name: voila
    component: voila
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: voila
{{- end -}}
