kind: ConfigMap
apiVersion: v1
metadata:
  name: daskernetes-config
data:
  worker-template.yaml: |-
    metadata:
      annotations:
        iam.amazonaws.com/role: "arn:aws:iam::536099501702:role/pangeo"
    spec:
      restartPolicy: Never
      containers:
        - name: dask-worker
          image: {{ .Values.pangeo.jupyterhub.singleuser.image.name }}:{{ .Values.pangeo.jupyterhub.singleuser.image.tag }}
          args: [dask-worker, --nthreads, '1', --no-bokeh, --memory-limit, 6GB, --death-timeout, '60']
          resources:
            limits:
              cpu: "1"
              memory: 6G
            requests:
              cpu: "1"
              memory: 6G
          volumeMounts:
            - name: s3
              mountPath: /s3
            - name: scratch
              mountPath: /scratch
          nodeSelector:
            aks-pangeon1-10905646-vmss000000: "true"
      volumes:
        - name: s3
          flexVolume:
            driver: "informaticslab/pysssix-flex-volume"
            options:
              readonly: "true"
        - name: scratch
          flexVolume:
            driver: "informaticslab/goofys-flex-volume"
            options:
              bucket: "informatics-pangeo-scratch"
              dirMode: "0777"
              fileMode: "0777"
