apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ${CERTIFICATE_AUTHORITY_DATA}
    server: https://api.cluster.${CLUSTER_URL}
  name: cluster.${CLUSTER_URL}
contexts:
- context:
    cluster: cluster.${CLUSTER_URL}
    user: cluster.${CLUSTER_URL}
  name: cluster.${CLUSTER_URL}
current-context: cluster.${CLUSTER_URL}
kind: Config
preferences: {}
users:
- name: cluster.${CLUSTER_URL}
  user:
    client-certificate-data: ${CLIENT_CERTIFICATE_DATA}
    client-key-data: ${CLIENT_KEY_DATA}
    password: ${PASSWORD}
    username: ${USERNAME}
- name: cluster.${CLUSTER_URL}-basic-auth
  user:
    password: ${PASSWORD}
    username: ${USERNAME}